dlar/account/urls.py
from django.urls import path, include
from . import views

app_name = 'dlar'
urlpatterns = [
    # path('', views.home, name='home'),
    # path('signin/', views.signin, name='signin'),
    # path('register/', views.register, name='register'),
    # path('adduser', views.add_user, name='add')
]

dlar/dlar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
]

dlar/login/urls.py
# from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'login'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.base_view, name='base'),
    path('login/', views.login_view, name='login')
]

dlar/account/models.py
from django.db import models


# Create your models here.
# class Account(models.Model):
#     user_name = models.CharField(max_length=100, blank=True, null=False)
#     user_email = models.EmailField(max_length=255, blank=True, null=False)
#     user_password = models.CharField(max_length=50, blank=True, null=False)

dlar/login/models.py
from django.db import models

# Create your models here.

dlar/account/forms.py
from django import forms
# from .models import Account
#
#
# class RegisterForm(forms.ModelForm):
#     class Meta:
#         model = Account
#         fields = ('user_name', 'user_email', 'user_password', 'user_password',)
#         widgets = {
#             'user_name': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
#             'user_email': forms.EmailInput(attrs={'class': 'form-control form-control-lg'}),
#             'user_password': forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}),
#             'user_password': forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'autocomplete': 'off', 'data-toggle': 'password'}),
#         }
#
#
# class SigninForm(forms.ModelForm):
#     class Meta:
#         model = Account
#         fields = ('user_name', 'user_password',)
#         widgets = {
#             'user_name': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
#             'user_password': forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}),
#         }

dlar/login/forms.py
from django.contrib.auth.models import User
from django import forms


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', ]
        widget = {'password': forms.PasswordInput()}

dlar/account/views.py
from django.shortcuts import render
from django.http import HttpResponse
# from .forms import RegisterForm, SigninForm
#
#
# # Create your views here.
# def home(request):
#     return render(request, 'account/home.html')
#
#
# def signin(request):
#     s = SigninForm()
#     context = {'s': s}
#     return render(request, 'account/signin.html', context)
#
#
# def register(request):
#     r = RegisterForm()
#     context = {'r': r}
#     return render(request, 'account/register.html', context)
#
#
# def add_user(request):
#     if request.method == 'POST':
#         u = RegisterForm(request.POST)
#         if u.is_valid():
#             u.save()
#             return HttpResponse('Dang ki thanh cong')

dlar/login/views.py
from django.shortcuts import render, HttpResponse
from django.views import View, generic
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from . import forms


# Create your views here.
class BaseView(View):
    template_name = 'login/base.html'


def base_view(request):
    template_name = 'login/base.html'
    return render(request, template_name)


def login_view(request):
    template_name = 'login/login.html'
    login_form = forms.LoginForm()
    context = {'login_form': login_form}
    return render(request, template_name, context)

dlar/login/templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'login:base' %}">Login and Register Django Project</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="#">About</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'login:login' %}">Login</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="#">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
    <!-- Footer -->
    <footer class="py-3 bg-grey">
        <p class="m-0 text-dark text-center ">Copyright &copy; Thang Truong</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

dlar/login/templates/login/login.html
{% extends "login/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 card mb-3  mt-3 ">
            <form method="post" style="margin-top: 1.3em; margin-bottom: 1.3em">
            {{ login_form | crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        </div>

    </div>
</div>

{%endblock%}